version: '3.7'
services:
  environment-redis:
    image: 'redis:alpine'
    container_name: redis_spotify
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6380:6379'
    networks:
      - environment-network

  environment-db:
    container_name: environment
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: environment
    ports:
      - "3306:3306"
    networks:
      - environment-network
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
  environment-be:
    depends_on:
      - environment-db
      - environment-redis
    image: truongnh28/environment
    container_name: environment-bee
    restart: always
    ports:
      - "8080:8080"
    networks:
      - environment-network
networks:
  environment-network: